# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chat' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  # Pods for Chat
  pod 'Firebase/Core'
  
  target 'Chat-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Chat-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Chat-tvOS

  target 'Chat-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
